Develop
bender-wardrobe/Recast pull request #15
Opened 2017-06-08 15:34 UTC by LionZXY

2017-06-08 15:35 UTC, LionZXY commented on src/headers/Server.h
> +    CommandManager manager;
Конфликт вот тут

2017-06-08 15:36 UTC, LionZXY commented on src/headers/Server.h
> +    Server *getServer() { return this; }
И вот тут

2017-06-08 20:29 UTC, LionZXY commented on src/Main.cpp
> + * @mainpage
Гуд

2017-06-08 20:55 UTC, MatkovIvan requested changes

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> +    return 0;
You may use `EXIT_SUCCESS` here.

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> +#include "stdio.h"
For systems headers you should use `<>` instead `""`. And `""` for your own headers.

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> +int main(){
Missing space before `{` and standard parameters. May be pass it to `initServer` for possible customize?

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> + * @file
Missing filename.

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> + * Init config class @see Config
Missing dot.

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> + * @author LionZXY
Email?

2017-06-08 20:55 UTC, MatkovIvan commented on src/Main.cpp
> +    delete server;
Why do you use dynamic allocation here?

2017-06-08 20:55 UTC, MatkovIvan commented on src/Server.cpp
> +#include "./headers/Server.h"
It looks wrong. May be just `"Server.h"`?

2017-06-08 20:55 UTC, MatkovIvan commented on src/Server.cpp
> +            BOOST_LOG_TRIVIAL(info) << "Папка " << dir << " создана успешно";
Cyrillic symbols in source code is bad practice. If you want localize this, you should use some resource file. OR just header with constants.

2017-06-08 20:55 UTC, MatkovIvan commented on src/Server.cpp
> +Server *Server::initServer() {
`void Server::initServer(Server * server)`
and
`Server server; Server::initServer(&server);`
in main.

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +        std::stringstream ss;
`std` namespace already used. It related to all entries in this file.

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +    for (int i = 0; i < commands.size(); i++)
Don't skip curly braces. It's way to bugs in the future.

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +using namespace std;
Harmonize blank lines usage with other files

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +bool StopCommand::isValid(std::string cmd, vector<string> args) {
Copy for check ?!? Use `const &`!

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +void StopCommand::onCommand(ICommandSender &sender, string cmd, vector<string> args) {
`const &`

2017-06-08 20:55 UTC, MatkovIvan commented on src/core/configs/Config.cpp
> +Config::Config(std::string filename) {
`const &`

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/Server.h
> +using namespace std;
MUST DON'T USE THIS IN HEADERS!

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/Server.h
> +    bool isOP() { return true; };
`;`?

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/commands/ICommand.h
> +using namespace std;
Must be removed too

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +using namespace std;
Must be removed too

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +#include <models/Player.h>
This is not system header. `""`

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +    ~ICommandSender() {}
nitpick: Why this before constructor?

2017-06-08 20:55 UTC, MatkovIvan commented on src/headers/configs/Config.h
> +using std::shared_ptr;
Using in header

2017-06-08 21:07 UTC, reo7sp requested changes
Ща сам поправлю критическое по-быстрому

2017-06-08 21:07 UTC, reo7sp commented on .gitignore
> +.gitignore
Эт че такое

2017-06-08 21:07 UTC, reo7sp commented on src/Main.cpp
> + * @brief Main method :)
:)

2017-06-08 21:07 UTC, reo7sp commented on src/Server.cpp
> +    std::string output = (std::string("recast_") + std::to_string(time(NULL)) + std::string(".log"));
Ну не надо стесняться использовать `using namespace std;` в *.cpp файлах. В *.h следует стесняться, да

2017-06-08 21:07 UTC, reo7sp commented on src/Server.cpp
> +    std::string output = (std::string("recast_") + std::to_string(time(NULL)) + std::string(".log"));
Не стоит оборачивать литералы строк в конструктор `string(...)`. Non-explicit конструктор стринга сам умеет неявно превращать `const char*` в `string`.

2017-06-08 21:07 UTC, reo7sp commented on src/Server.cpp
> +Server *Server::initServer() {
TODO для @reo7sp: написать мини-стайлгайд рекаста, в котором звездочки стоят у типа. Ну, так же логичнее и приятнее.
Можно сказать, что я не прав, если что.

2017-06-08 21:07 UTC, reo7sp commented on src/core/commands/CommandManager.cpp
> +namespace {
Пустую строчку бы после юзинга, чтобы дышать было легче

2017-06-08 21:07 UTC, reo7sp commented on src/core/commands/CommandManager.cpp
> +        std::stringstream ss;
`std::` можно опустить

2017-06-08 21:07 UTC, reo7sp commented on src/core/commands/CommandManager.cpp
> +    vector <string> cmds = split(cmd, ' ');
Лишний пробельчик

2017-06-08 21:07 UTC, reo7sp commented on src/core/commands/ICommand.cpp
> + * Now do nothing :3
:3

2017-06-08 21:07 UTC, reo7sp commented on src/core/configs/Config.cpp
> +        INSTANCE = shared_ptr<Config>(new Config(DEFAULT_CONFIG));
Кстати, оказывается `std::make_shared` лучше. В https://stackoverflow.com/a/20895705 объяснено. Кратко:
1. Объект и счетчик находятся рядышком в одном участке памяти, что производительнее.
2. Безопаснее реагирует на исключения.

2017-06-08 21:07 UTC, reo7sp commented on src/headers/Server.h
> +using namespace std;
Низя, низя! Этот юзинг срабатывает во всех файлах, которые инклудят этот. А им это может быть и не надо. Так случается, потому что #include – это тоже самое, что скопипастить и подставить содержимое.

2017-06-08 21:07 UTC, reo7sp commented on src/headers/Server.h
> +    shared_ptr<Server> getServer() { return shared_ptr<Server>(this); }
Ой, ой. Нельзя оборачивать this в shared_ptr. Когда этот птр умрет, он унесет с собой this.

Простой пример, как прострелить ногу:
```
auto server = сервер;
if (smth) {
  auto s = getServer();
}
бдыщ
```

Решение проблемы: http://ru.cppreference.com/w/cpp/memory/enable_shared_from_this

2017-06-08 21:20 UTC, reo7sp approved these changes

2017-06-08 21:27 UTC, reo7sp commented
>LionZXY  wants to merge 28 commits into master from develop
Ну и смысл в этом develop, когда ты все равно всё льешь в мастер? В таком случае develop – это одна из фича-веток, разве что с абстрактным, нечетким названием, а не тот develop из git flow.

2017-06-08 21:30 UTC, LionZXY commented
@reo7sp Я архитектор, я так вижу

2017-06-08 21:40 UTC, LionZXY commented on src/core/configs/Config.cpp
> +        INSTANCE = shared_ptr<Config>(new Config(DEFAULT_CONFIG));
Переводим все на make_shared?

2017-06-09 06:23 UTC, LionZXY commented on src/Main.cpp
> + * @author LionZXY
@email ?

2017-06-09 06:25 UTC, LionZXY commented on src/Main.cpp
> +int main(){
Yup.

2017-06-09 06:33 UTC, LionZXY commented on src/Main.cpp
> + * @file
Fix in future

2017-06-09 07:25 UTC, LionZXY commented on src/Server.cpp
> +    std::string output = (std::string("recast_") + std::to_string(time(NULL)) + std::string(".log"));
Сам попробуй эту строку написать без конструкторов

2017-06-09 07:25 UTC, LionZXY commented on src/Server.cpp
> +Server *Server::initServer() {
Нет. Так ставит CLion

2017-06-09 08:27 UTC, LionZXY commented on src/Server.cpp
> +        this->getServer();
Не понимаю почему тут крашиться с ошибкой Invalid Pointer

2017-06-09 08:36 UTC, LionZXY commented on src/core/commands/ICommand.cpp
> + * Now do nothing :3
:3

2017-06-09 08:43 UTC, StealthTech approved these changes

2017-06-09 11:38 UTC, MatkovIvan requested changes

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +        std::stringstream ss;
~std::~

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +void CommandManager::onCommand(ICommandSender *sender, std::string cmd) {
`const string &`

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +bool StopCommand::isValid(string &cmd, vector<string> args) {
`const &` x2

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +void StopCommand::onCommand(ICommandSender &sender, string &cmd, vector<string> args) {
`const &` x2

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/configs/Config.cpp
> +#include <configs/Config.h>
`""`

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/Server.h
> +    bool isOP() { return true; };
const function

2017-06-09 11:38 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +bool StopCommand::isValid(string &cmd, vector<string> args) {
const function

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/Server.h
> +    std::shared_ptr<Server> getServer() { return std::shared_ptr<Server>(this); }
const function

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/Server.h
> +    std::shared_ptr<Player> getPlayer() { return std::shared_ptr<Player>(NULL); }
const function

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/commands/ICommand.h
> +    virtual bool isValid(std::string &cmd, std::vector<std::string> args) = 0; //// You should return @var True if this command line satisfied with you.
`const &` x2

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/commands/ICommand.h
> +    virtual void onCommand(ICommandSender &sender, std::string &cmd, std::vector<std::string> args) = 0;
`const &`

2017-06-09 11:38 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +    ~ICommandSender() {}
virtual

2017-06-09 15:45 UTC, MatkovIvan requested changes

2017-06-09 15:45 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +    commands.push_back(std::make_shared<StopCommand>());
~std::~

2017-06-09 15:45 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +    std::vector<int> valid;
~std::~

2017-06-09 15:45 UTC, MatkovIvan commented on src/core/configs/Config.cpp
> +static shared_ptr<Config> INSTANCE = NULL;
~shared_ptr~

2017-06-09 15:45 UTC, MatkovIvan commented on src/core/configs/Config.cpp
> +    if (INSTANCE != NULL)
```
if (!INSTANCE) {
    INSTANCE = make_shared<Config>(DEFAULT_CONFIG);
}
return INSTANCE;
```

2017-06-09 15:45 UTC, MatkovIvan commented on src/core/configs/Config.cpp
> +Config::~Config() {
It seems that it will never be called

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/Server.h
> +    Server(Server &other) = delete;
`const`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/Server.h
> +#include "models/Player.h"
Redundant. You may use just `class Player;`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/Server.h
> +#include <memory>
Redundant, but `<string>` is missed.

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/commands/CommandManager.h
> +#include "ICommandSender.h"
Redundant. You may use just `class ICommandSender;`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/commands/CommandManager.h
> +#include "ICommand.h"
Redundant. You may use just `class ICommand;`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/commands/CommandManager.h
> +    std::vector<std::shared_ptr<ICommand>> commands;
Missing include for `vector` and `shared_ptr`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/commands/ICommand.h
> +    ICommand(const ICommand &other) {}
Why do you need this?

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +#include <boost/shared_ptr.hpp>
Redundant

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/configs/Config.h
> +    Config(std::string filename);
`const &`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/configs/Config.h
> +    Config(Config &other) = delete;
`const`

2017-06-09 15:45 UTC, MatkovIvan commented on src/headers/configs/Config.h
> +    std::string filename;
Missing include for this.

2017-06-09 15:59 UTC, LionZXY commented on src/headers/configs/Config.h
> +    std::string filename;
Fix it

2017-06-09 16:00 UTC, LionZXY commented on src/headers/commands/ICommand.h
> +    ICommand(const ICommand &other) {}
Copy object optimization

2017-06-09 16:00 UTC, LionZXY commented on src/headers/commands/CommandManager.h
> +    std::vector<std::shared_ptr<ICommand>> commands;
Fix it

2017-06-09 16:00 UTC, LionZXY commented on src/headers/Server.h
> +#include <memory>
Fix it

2017-06-09 16:01 UTC, LionZXY commented on src/core/configs/Config.cpp
> +Config::~Config() {
Now called in Server destructor

2017-06-09 17:25 UTC, MatkovIvan requested changes

2017-06-09 17:25 UTC, MatkovIvan commented on src/Server.cpp
> +#include <configs/Config.h>
`""`

2017-06-09 17:25 UTC, MatkovIvan commented on src/Server.cpp
> +#include <configs/Config.h>
`""`

2017-06-09 17:25 UTC, MatkovIvan commented on src/headers/Server.h
> +#include <memory>
Nope. `<memory>` still here

2017-06-09 18:16 UTC, MatkovIvan requested changes

2017-06-09 18:16 UTC, MatkovIvan commented on src/headers/commands/CommandManager.h
> +    CommandManager(CommandManager &other) = delete;
`const`

2017-06-09 18:16 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +    ICommandSender() {}
Redundant

2017-06-09 18:16 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +    if (valid.size() == 0)
`{}`

2017-06-09 18:16 UTC, MatkovIvan commented on src/core/commands/CommandManager.cpp
> +    for (int i = 0; i < commands.size(); i++)
`{}`

2017-06-09 18:16 UTC, MatkovIvan commented on src/Server.cpp
> +    if (!boost::filesystem::exists(dir))
`{}`

2017-06-09 18:16 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +    sender.getPlayer();
WTF?

2017-06-09 18:16 UTC, MatkovIvan commented on src/core/commands/StopCommand.cpp
> +        sender.getServer()->isRunning = false;
Encapsulation?

2017-06-09 18:16 UTC, MatkovIvan commented on src/headers/commands/ICommandSender.h
> +    virtual Player *getPlayer() = 0;
`const`?

2017-06-09 18:18 UTC, LionZXY commented on src/headers/commands/ICommandSender.h
> +    virtual Player *getPlayer() = 0;
No

2017-06-09 18:19 UTC, LionZXY commented on src/core/commands/StopCommand.cpp
> +    sender.getPlayer();
OMG

2017-06-09 18:19 UTC, LionZXY commented on src/core/commands/StopCommand.cpp
> +        sender.getServer()->isRunning = false;
Singleton?

2017-06-09 18:19 UTC, MatkovIvan approved these changes

2017-06-09 18:30 UTC, merged

2017-06-09 18:33 UTC, reo7sp commented on src/headers/commands/ICommand.h
> +    ICommand(const ICommand &other) {}
шо