Added network integration and refactored header files
bender-wardrobe/Recast pull request #34
Opened 2017-06-19 00:45 UTC by StealthTech

+ Added NetworkServer class
~ Integrated NetworkServer to Server
~ Now all network files lie in proper directories
~ Renamed .h files to .hpp (refactored links)
~ Minor refactoring

2017-06-19 01:15 UTC, Ansile submitted a review, later dismissed

2017-06-19 06:12 UTC, LionZXY commented on src/core/network/Networking.cpp
> +    int sd = socket(/*Protocol Family*/PF_INET, SOCK_STREAM, IPPROTO_TCP);
Хиде моя хотелка с TCP/UDP?

2017-06-19 06:12 UTC, LionZXY commented on src/core/network/Networking.cpp
> +        throw std::runtime_error("error to create socket: " + std::string(strerror(errno)));
С большой буквы?

2017-06-19 06:12 UTC, LionZXY commented on src/core/network/Networking.cpp
> +std::string Socket::recvTimed(int timeout) throw (std::exception) {
```
using namespace std;
```

2017-06-19 06:12 UTC, LionZXY commented on src/headers/network/Networking.hpp
> +#define DEFAULT_PORT 1337
Лучше использовать константы

2017-06-19 06:12 UTC, LionZXY commented on src/headers/network/Networking.hpp
> +public:
Нужно ли столько методов в public?

2017-06-19 07:54 UTC, LionZXY commented
Сделай ещё, пожалуйста, возможность приема байтового потока (или опционально, или вместо строки)

2017-06-19 08:33 UTC, StealthTech commented on src/core/network/Networking.cpp
> +        throw std::runtime_error("error to create socket: " + std::string(strerror(errno)));
Socket?

2017-06-20 08:11 UTC, LionZXY commented
Наверно, лучше сделать примерно так:
```
NetworkServer *udp = new NetworkServer(123);
NetworkServer *tcp = new NetworkServer(124, true);
```

2017-06-22 19:44 UTC, LionZXY requested changes

2017-06-22 19:44 UTC, LionZXY commented on src/Server.cpp
> +    listenUDPThread = thread(&Server::runNetworkServer, this, serverUDP);
Это плохо. Лучше просто вызывать метод и уже в самом методе распараллеливать

2017-06-22 19:44 UTC, LionZXY commented on src/Server.cpp
> +    server->run();
Типо
```
thread(&NetworkServer::run, server);
```
Тоже самое, а принцип SOLID соблюдается лучше
P.S. Не тоже самое

2017-06-22 19:44 UTC, LionZXY commented on src/headers/network/NetworkServer.hpp
> +    bool isRunning;
Если переменная изменяется из нескольких потоков, надо сделать её  volatite

2017-06-22 19:44 UTC, LionZXY commented on src/Server.cpp
> +    delete serverTCP;
Нельзя тут delete. Размести в конструкторе. Shutdown Lock-free метод (может выполняться в другом потоке). Может произойти ппц, если удалять вот так. Размести это в деструкторе. (К тому же, ты можешь вызвать деструктор раньше, чем закончиться выполнение (у тебя же цикл))
Советую перенести в деструктор и сделать примерно так:
```
while(serverTCP->isRunning());
delete serverTCP;
```

2017-06-22 19:44 UTC, LionZXY commented on src/core/network/NetworkServer.cpp
> +            string request = client->recv();
Я вроде просил все переделать в байтовый массив

2017-06-22 19:53 UTC, LionZXY commented on src/Server.cpp
> +    delete serverTCP;
Фигню сморозил. Не надо

2017-06-22 20:51 UTC, reo7sp commented on src/headers/network/NetworkServer.hpp
> +    bool isRunning;
@LionZXY ну или завернуть в std::atomic

2017-06-22 21:14 UTC, LionZXY requested changes

2017-06-22 21:14 UTC, LionZXY commented on src/Server.cpp
> +    while (serverUDP->running());
Я фигню сморозил, сказал жи ;) Этого не надо

2017-06-22 21:18 UTC, LionZXY approved these changes

2017-06-22 21:22 UTC, merged