Spell casting
bender-wardrobe/Recast pull request #49
Opened 2017-06-24 12:56 UTC by LionZXY

2017-06-24 15:00 UTC, Ansile requested changes
Необходим рефакторинг названий классов: Node -> SpellNode. Spell - обязательно единичный граф, т.е. не может быть больше одного контура? Если нет, то архитектура класса некорректна

2017-06-24 15:04 UTC, Ansile commented
И да, подумай о использовании double в арифметике, при использовании float в больших формулах будет потеря точности.

2017-06-24 15:17 UTC, LionZXY commented
Не может быть больше одного контура. Это условие такое изначально. Если нужны два независимых контура - соеденяем их обычной нодой

2017-06-24 15:17 UTC, LionZXY commented
Точность не так важна как быстродействие в данном случае. Да, точность совсем не важна.

2017-06-24 15:19 UTC, Ansile commented
Окей, по поводу деструктора ~Node тогда - если контур зациклен в каком-то месте, некоторые указатели могут очиститься дважды, что не есть хорошо.

2017-06-24 15:20 UTC, LionZXY commented
Посмотри внимательнее

2017-06-24 15:24 UTC, Ansile commented
На что смотреть? У тебя с одной и с другой ноды придёт запрос, если в цикле. Первая нода очистила указатель, вторая - обращается по пустому указателю и пытается получить nowInTick. Дальше идёт undefined behaviour.

2017-06-24 15:26 UTC, LionZXY commented
Еще раз посмотри. У нас рекурсия создается, в которую не входят те ноды, которые nowInTick = true.

2017-06-24 16:15 UTC, Ansile approved these changes

2017-06-24 16:18 UTC, LionZXY commented
А перевести доки?

2017-06-24 16:28 UTC, merged

2017-06-25 17:17 UTC, reo7sp commented on temperature-world/test/lib/crow_all.h
> +/* Copyright Joyent, Inc. and other SpellNode contributors. All rights reserved.
)))

2017-06-25 17:20 UTC, LionZXY commented on temperature-world/test/lib/crow_all.h
> +/* Copyright Joyent, Inc. and other SpellNode contributors. All rights reserved.
Лель, орнул